let nombre = "Mai";
let apellido = "Bracken";
let edad = 20;
let numeroDeTelefono = "2355501571";
let socio = true;
let fechaDelPartido = "10/01/2023";
let horaDelPartido = "20:30";
let numeroDeSilla = 7;
let precioDelBoleto = 30.5;
console.log(nombre, apellido, edad, numeroDeTelefono, socio, fechaDelPartido, horaDelPartido, numeroDeSilla, precioDelBoleto);
console.log(typeof(nombre));
console.log(typeof(apellido));
console.log(typeof(edad));
console.log(typeof(numeroDeTelefono));
console.log(typeof(socio));
console.log(typeof(fechaDelPartido));
console.log(typeof(horaDelPartido));
console.log(typeof(numeroDeSilla));
console.log(typeof(precioDelBoleto));